/**
 * E2E Smoke Tests - gomonto
 * Generated by InoPay NCS 2.0
 */
import { describe, it, expect, beforeAll } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';
const APP_URL = process.env.APP_URL || 'http://localhost:5173';

describe('E2E Smoke Tests', () => {
  beforeAll(async () => {
    // Wait for services to be ready
    let attempts = 0;
    while (attempts < 30) {
      try {
        const res = await fetch(`${API_URL}/health`);
        if (res.ok) break;
      } catch (e) {
        await new Promise(r => setTimeout(r, 1000));
        attempts++;
      }
    }
  });
  
  it('API health check passes', async () => {
    const res = await fetch(`${API_URL}/health`);
    expect(res.ok).toBe(true);
    const data = await res.json();
    expect(data.status).toBe('healthy');
  });
  
  it('Frontend serves HTML', async () => {
    const res = await fetch(APP_URL);
    expect(res.ok).toBe(true);
    expect(res.headers.get('content-type')).toContain('text/html');
  });

  it('Route ai_damage_detection is reachable', async () => {
    const res = await fetch(`${API_URL}/api/ai_damage_detection`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route cinetpay_check_status is reachable', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_check_status`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route cinetpay_initiate is reachable', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_initiate`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route cinetpay_webhook is reachable', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_webhook`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('Route compliance_notifications is reachable', async () => {
    const res = await fetch(`${API_URL}/api/compliance_notifications`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
});
