/**
 * Smoke Tests - gomonto
 * Generated by InoPay Liberation Pack NCS
 */
import { describe, it, expect } from 'vitest';

const API_URL = process.env.API_URL || 'http://localhost:3000';

describe('API Smoke Tests', () => {
  it('health check', async () => {
    const res = await fetch(`${API_URL}/health`);
    expect(res.status).toBe(200);
  });

  it('ai_damage_detection responds', async () => {
    const res = await fetch(`${API_URL}/api/ai_damage_detection`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('cinetpay_check_status responds', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_check_status`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('cinetpay_initiate responds', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_initiate`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('cinetpay_webhook responds', async () => {
    const res = await fetch(`${API_URL}/api/cinetpay_webhook`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('compliance_notifications responds', async () => {
    const res = await fetch(`${API_URL}/api/compliance_notifications`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('generate_condition_report responds', async () => {
    const res = await fetch(`${API_URL}/api/generate_condition_report`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('generate_contract responds', async () => {
    const res = await fetch(`${API_URL}/api/generate_contract`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('ical_sync responds', async () => {
    const res = await fetch(`${API_URL}/api/ical_sync`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('initiate_payment responds', async () => {
    const res = await fetch(`${API_URL}/api/initiate_payment`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
  it('kyc_document_access responds', async () => {
    const res = await fetch(`${API_URL}/api/kyc_document_access`, { method: 'OPTIONS' });
    expect([200, 204, 401, 405]).toContain(res.status);
  });
});